apiVersion: batch/v1
kind: Job
metadata:
  name: low-priority-job-outside-fence
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      labels:
        applicationId: low-priority-job-outside-fence
        queue: root.sandbox.system.system-low
    spec:
      schedulerName: yunikorn
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.7
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
      restartPolicy: Never
